Ensure python is available to action
Signed-off-by: Andy Doan <andy@foundries.io>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -25,6 +25,25 @@ outputs:
 runs:
   using: "composite"
   steps:
+    - name: Setup Python
+      shell: bash
+      run: |
+        set -eu
+
+        which python >/dev/null 2>&1 && exit 0
+        echo "Python not found. Installing..."
+
+        which apt >/dev/null 2>&1 || (echo "ERROR: This action requires 'apt'"; exit 1)
+
+        apt="apt"
+        if [ `id -u` -ne 0 ] ; then
+            which sudo >/dev/null 2>&1 || (echo "ERROR: This action needs 'sudo'"; exit 1)
+            apt="sudo apt"
+        fi
+
+        ${apt} update
+        ${apt} -y install python3 python3-requests
+
     - name: Upload Artifacts
       id: upload
       env:
@@ -34,7 +53,4 @@ runs:
         GITHUB_TOKEN: ${{ inputs.github_token }}
         UPLOAD_THREADS: ${{ inputs.upload_threads }}
       shell: bash
-      run: |
-        set -ex
-        python -m pip install requests
-        python ${GITHUB_ACTION_PATH}/publish_artifacts.py
+      run: python ${GITHUB_ACTION_PATH}/publish_artifacts.py
