Try to install requests if its missing
Signed-off-by: Andy Doan <andy@foundries.io>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -27,8 +27,14 @@ runs:
       run: |
         set -eu
 
-        which python >/dev/null 2>&1 && exit 0
-        echo "Python not found. Installing..."
+        if python >/dev/null 2>&1 ; then
+            if ! python -c "import requests" 2>/dev/null ; then
+                echo "= Python requests not found. Installing with pip"
+                python3 -m pip install requests
+            fi
+            exit 0
+        fi
+        echo "= Python not found. Installing..."
 
         which apt >/dev/null 2>&1 || (echo "ERROR: This action requires 'apt'"; exit 1)
 
